services:
  user:
    build:
      dockerfile: ./apps/user/Dockerfile
      context: .
      target: development
    command: npm run start:dev user
    env_file:
      - ./apps/user/.development.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      user-db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  token:
    build:
      dockerfile: ./apps/token/Dockerfile
      context: .
      target: development
    command: npm run start:dev token
    env_file:
      - ./apps/token/.development.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      token-db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.development.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      user:
        condition: service_started
      token:
        condition: service_started
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev gateway
    env_file:
      - ./apps/gateway/.development.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      user:
        condition: service_started
      token:
        condition: service_started
      auth:
        condition: service_started
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  user-db:
    image: postgres:latest
    container_name: user-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: user_service_password
      POSTGRES_DB: user_service_db
    volumes:
      - ./docker-entrypoint-initdb.d/user:/docker-entrypoint-initdb.d
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U user_service_user -d user_service_db' ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  token-db:
    image: postgres:latest
    container_name: token-db
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: token_service_user
      POSTGRES_PASSWORD: token_service_password
      POSTGRES_DB: token_service_db
    volumes:
      - ./docker-entrypoint-initdb.d/token:/docker-entrypoint-initdb.d
      - token_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U token_service_user -d token_service_db' ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
      - PGADMIN_LOG_LEVEL=ERROR
    user: '$UID:$GID'
    env_file:
      - .psql.dev.env
    depends_on:
      user-db:
        condition: service_healthy
      token-db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    healthcheck:
      test: [ 'CMD', 'rabbitmq-diagnostics', 'ping' ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

networks:
  default:
    driver: bridge

volumes:
  user_postgres_data: {}
  token_postgres_data: {}
