services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .development.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    user: '$UID:$GID'
    env_file:
      - .development.env
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  user:
    build:
      dockerfile: ./apps/user/Dockerfile
      context: .
      target: development
    command: npm run start:dev user
    env_file:
      - ./apps/user/.env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

networks:
  default:
    driver: bridge

volumes:
  postgres_data: {}
